[colors.bright]
black = "0x2d3437"
blue = "0x71baf2"
cyan = "0x67cbe7"
green = "0x96d988"
magenta = "0xce89df"
red = "0xef7e7e"
white = "0xbdc3c2"
yellow = "0xf4d67a"

[colors.cursor]
cursor = "0x3b4244"
text = "0xd6d6d6"

[colors.normal]
black = "0x232a2d"
blue = "0x67b0e8"
cyan = "0x6cbfbf"
green = "0x8ccf7e"
magenta = "0xc47fd5"
red = "0xe57474"
white = "0xb3b9b8"
yellow = "0xe5c76b"

[colors.primary]
background = "0x141b1e"
foreground = "0xdadada"

[cursor]
style = "Block"

[font]
size = 18.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.9
